### ISSUE TITLE
cant get plugin to load old versions or new

### ISSUE THREAD

**Issue by Stoniasawsome** [poma123/GlobalWarming#11]
## Description (REQUIRED)
i downloaded 
GlobalWarming - DEV 4 (git bd8e7).jar
to my paper spigot server PaperMC-1.16.3.jar
i get this error when loading the plugin
ERROR Could not load 'plugins/GlobalWarming - DEV 4 (git bd8e7).jar' in folder 'plugins'
23.11 12:44:56 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: me/mrCookieSlime/CSCoreLibPlugin/cscorelib2/updater/Updater
23.11 12:44:56 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.3.jar:git-Paper-253]
23.11 12:44:56 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.3.jar:git-Paper-253]
23.11 12:44:56 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.3.jar:git-Paper-253]
23.11 12:44:56 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.3.jar:git-Paper-253]
23.11 12:44:56 [Server] INFO at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:204) ~[patched_1.16.3.jar:git-Paper-253]
23.11 12:44:56 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-253]
23.11 12:44:56 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-253]
23.11 12:44:56 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]
23.11 12:44:56 [Server] INFO Caused by: java.lang.NoClassDefFoundError: me/mrCookieSlime/CSCoreLibPlugin/cscorelib2/updater/Updater
23.11 12:44:56 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:?]
23.11 12:44:56 [Server] INFO at java.lang.Class.forName(Class.java:398) ~[?:?]
23.11 12:44:56 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.16.3.jar:git-Paper-253]
23.11 12:44:56 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.3.jar:git-Paper-253]
23.11 12:44:56 [Server] INFO ... 7 more
23.11 12:44:56 [Server] INFO Caused by: java.lang.ClassNotFoundException: me.mrCookieSlime.CSCoreLibPlugin.cscorelib2.updater.Updater
23.11 12:44:56 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
23.11 12:44:56 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.3.jar:git-Paper-253]
23.11 12:44:56 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.3.jar:git-Paper-253]
23.11 12:44:56 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
23.11 12:44:56 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
23.11 12:44:56 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:?]
23.11 12:44:56 [Server] INFO at java.lang.Class.forName(Class.java:398) ~[?:?]
23.11 12:44:56 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.16.3.jar:git-Paper-253]
23.11 12:44:56 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.3.jar:git-Paper-253]
23.11 12:44:56 [Server] INFO ... 7 more
--

## Steps to reproduce the Issue (REQUIRED)

as stated above i downloaded the plugin and this is what i got on startup

## Expected behavior (REQUIRED)

i expected the plugin would work

## Server Log

ERROR Could not load 'plugins/GlobalWarming - DEV 4 (git bd8e7).jar' in folder 'plugins'
23.11 12:44:56 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: me/mrCookieSlime/CSCoreLibPlugin/cscorelib2/updater/Updater
23.11 12:44:56 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.3.jar:git-Paper-253]
23.11 12:44:56 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.3.jar:git-Paper-253]
23.11 12:44:56 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.3.jar:git-Paper-253]
23.11 12:44:56 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.3.jar:git-Paper-253]
23.11 12:44:56 [Server] INFO at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:204) ~[patched_1.16.3.jar:git-Paper-253]
23.11 12:44:56 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-253]
23.11 12:44:56 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-253]
23.11 12:44:56 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]
23.11 12:44:56 [Server] INFO Caused by: java.lang.NoClassDefFoundError: me/mrCookieSlime/CSCoreLibPlugin/cscorelib2/updater/Updater
23.11 12:44:56 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:?]
23.11 12:44:56 [Server] INFO at java.lang.Class.forName(Class.java:398) ~[?:?]
23.11 12:44:56 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.16.3.jar:git-Paper-253]
23.11 12:44:56 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.3.jar:git-Paper-253]
23.11 12:44:56 [Server] INFO ... 7 more
23.11 12:44:56 [Server] INFO Caused by: java.lang.ClassNotFoundException: me.mrCookieSlime.CSCoreLibPlugin.cscorelib2.updater.Updater
23.11 12:44:56 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
23.11 12:44:56 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.3.jar:git-Paper-253]
23.11 12:44:56 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.3.jar:git-Paper-253]
23.11 12:44:56 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
23.11 12:44:56 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
23.11 12:44:56 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:?]
23.11 12:44:56 [Server] INFO at java.lang.Class.forName(Class.java:398) ~[?:?]
23.11 12:44:56 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.16.3.jar:git-Paper-253]
23.11 12:44:56 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.3.jar:git-Paper-253]
23.11 12:44:56 [Server] INFO ... 7 more

## /error-reports/ Folder

i got ton of errors in this folder, ill give you the first one. most of them are from this void panel item

Java Environment:
  Operating System: Linux
  Java Version: 11.0.2

Server Software: Paper
  Build: git-Paper-253 (MC: 1.16.3)
  Minecraft v1.16.3-R0.1-SNAPSHOT

Slimefun Environment:
  CS-CoreLib v1.6.3
  Slimefun vDEV - 756 (git 354dd30e)
  Caused by: InfinityExpansion vDEV - 49 (git fe0b3707)

Installed Addons (31)
  + EcoPower DEV - 2 (git b0c0c875)
  + Barrels DEV - 14 (git 1563de94)
  + ExtraGear DEV - 12 (git 4570ea2c)
  - ClayTech 1.2.18
  + InfinityExpansion DEV - 49 (git fe0b3707)
  + SFCalc DEV - 14 (git 8d205b67)
  + MobCapturer DEV - 11 (git 4edf38dd)
  + TranscEndence DEV - 21 (git f7bb1376)
  + ChestTerminal DEV - 38 (git c024be5c)
  + SlimefunWarfare DEV - 9 (git fe18afc3)
  + HotbarPets DEV - 31 (git 5909202f)
  + ExoticGarden DEV - 61 (git b5067266)
  - Liquid DEV - 2 (git a1e713d8)
  + SoulJars DEV - 17 (git 9eedba0f)
  - AsteroidBelt 1.0.5
  + ExtraTools DEV - 22 (git ea11f88b)
  + FoxyMachines DEV - 7 (git 85598948)
  + SlimefunOreChunks DEV - 9 (git 88dd72b0)
  + MoreTools DEV - 8 (git db8d8814)
  + ElectricSpawners DEV - 18 (git f9da206b)
  + WhatIsThis 3.2
  + SlimyTreeTaps DEV - 15 (git 205f8afc)
  + PrivateStorage DEV - 14 (git 98a31c90)
  + ColoredEnderChests DEV - 17 (git f9a39e70)
  + FluffyMachines DEV - 45 (git 83a0ff9a)
  + DyedBackpacks DEV - 9 (git c42435c1)
  + SoundMuffler DEV - 17 (git 3abf8993)
  + SensibleToolbox DEV - 33 (git ca72a257)
  + LiteXpansion DEV - 98 (git f79eab2f)
  + CMI 8.7.10.0
  - SlimyPowerSuits DEV - 8 (git a93bd3ae)

Installed Plugins (61):
  + GroupManager 2.8 (Phoenix)
  + PlaceholderAPI 2.10.9
  + LightAPI 3.4.5
  + LoneLibs 1.0.5
  + ProtocolLib 4.6.0-SNAPSHOT-b480
  + LibsDisguises 10.0.19
  + ImageMaps 1.0.2
  + CS-CoreLib 1.6.3
  + AutoCraft 1.9
  + Vault 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
  + ScriptBlock 0.8.72
  + SellStick 1.16.1v1
  + ServerSigns 4.6.1
  + WorldEdit 7.2.0-SNAPSHOT+b9e750f
  + HeadDatabase 4.12.6
  + EmeraldEnchants DEV - 7 (git 3cd370b5)
  + WorldGuard 7.0.2-SNAPSHOT;1998-f43a4ea
  + Brewery 2.1.2
  + Slimefun DEV - 756 (git 354dd30e)
  + EcoPower DEV - 2 (git b0c0c875)
  + Barrels DEV - 14 (git 1563de94)
  + Shop 1.8.2.3
  + ExtraGear DEV - 12 (git 4570ea2c)
  - ClayTech 1.2.18
  + InfinityExpansion DEV - 49 (git fe0b3707)
  + SFCalc DEV - 14 (git 8d205b67)
  + MobCapturer DEV - 11 (git 4edf38dd)
  + TranscEndence DEV - 21 (git f7bb1376)
  + ChestTerminal DEV - 38 (git c024be5c)
  + SlimefunWarfare DEV - 9 (git fe18afc3)
  + HotbarPets DEV - 31 (git 5909202f)
  + ExoticGarden DEV - 61 (git b5067266)
  - Liquid DEV - 2 (git a1e713d8)
  + SoulJars DEV - 17 (git 9eedba0f)
  - AsteroidBelt 1.0.5
  + ExtraTools DEV - 22 (git ea11f88b)
  + FoxyMachines DEV - 7 (git 85598948)
  + SlimefunOreChunks DEV - 9 (git 88dd72b0)
  + MoreTools DEV - 8 (git db8d8814)
  + ElectricSpawners DEV - 18 (git f9da206b)
  + WhatIsThis 3.2
  + SlimyTreeTaps DEV - 15 (git 205f8afc)
  + PrivateStorage DEV - 14 (git 98a31c90)
  + ColoredEnderChests DEV - 17 (git f9a39e70)
  + FluffyMachines DEV - 45 (git 83a0ff9a)
  + DyedBackpacks DEV - 9 (git c42435c1)
  + SoundMuffler DEV - 17 (git 3abf8993)
  + SensibleToolbox DEV - 33 (git ca72a257)
  + Multiverse-Core 4.1.0-b775
  + LiteXpansion DEV - 98 (git f79eab2f)
  + CMI 8.7.10.0
  + CubCustomDrops 5.5.1
  - SlimyPowerSuits DEV - 8 (git a93bd3ae)
  + Towny 0.96.3.0
  + TownyChat 0.81
  + SpecializedCrates 2.12.7
  + ItemsAdder 2.1.15
  + TownyNameUpdater 5.0
  + WolfyUtilities 1.6.2.11
  + CustomCrafting 1.6.4.0
  + CMIPaperLib 1.0.0

Block Info:
  World: world
  X: 10045
  Y: 217
  Z: 9987
  Material: LIGHT_GRAY_GLAZED_TERRACOTTA
  Block Data: org.bukkit.craftbukkit.v1_16_R2.block.impl.CraftGlazedTerracotta
  State: org.bukkit.craftbukkit.v1_16_R2.block.CraftBlockState

Ticker-Info:
  Type: Synchronized

Ticker-Info:
  Type: Indirect (Energy Network)

Slimefun Data:
  ID: VOID_PANEL
  Inventory: true
  Data: {"energy-charge":"900000","id":"VOID_PANEL"}

Stacktrace:

java.lang.NoClassDefFoundError: me/mrCookieSlime/CSCoreLibPlugin/cscorelib2/collections/Pair
	at io.github.mooy1.infinityexpansion.implementation.machines.EnergyGenerator.getGeneratingAmount(EnergyGenerator.java:195)
	at io.github.mooy1.infinityexpansion.implementation.machines.EnergyGenerator.getGeneratedOutput(EnergyGenerator.java:117)
	at io.github.thebusybiscuit.slimefun4.core.networks.energy.EnergyNet.tickAllGenerators(EnergyNet.java:214)
	at io.github.thebusybiscuit.slimefun4.core.networks.energy.EnergyNet.tick(EnergyNet.java:129)
	at io.github.thebusybiscuit.slimefun4.implementation.items.electric.EnergyRegulator.tick(EnergyRegulator.java:75)
	at io.github.thebusybiscuit.slimefun4.implementation.items.electric.EnergyRegulator.access$000(EnergyRegulator.java:31)
	at io.github.thebusybiscuit.slimefun4.implementation.items.electric.EnergyRegulator$2.tick(EnergyRegulator.java:68)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:179)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickLocation(TickerTask.java:166)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:136)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:101)
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: me.mrCookieSlime.CSCoreLibPlugin.cscorelib2.collections.Pair
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 17 more

## Environment (REQUIRED)

23.11 12:50:18 [Multicraft] Steve_French_ ran command: sf versions
23.11 12:50:18 [Server] INFO This Server uses the following setup of Slimefun:
23.11 12:50:18 [Server] INFO Paper v1_16_R2
23.11 12:50:18 [Server] INFO CS-CoreLib v1.6.3
23.11 12:50:18 [Server] INFO Slimefun vDEV - 756 (git 354dd30e)
23.11 12:50:18 [Server] INFO Metrics build: #17
23.11 12:50:18 [Server] INFO Installed Addons: (31)
23.11 12:50:18 [Server] INFO SlimyPowerSuits vDEV - 8 (git a93bd3ae)
23.11 12:50:18 [Server] INFO AsteroidBelt v1.0.5
23.11 12:50:18 [Server] INFO ExtraTools vDEV - 22 (git ea11f88b)
23.11 12:50:18 [Server] INFO FoxyMachines vDEV - 7 (git 85598948)
23.11 12:50:18 [Server] INFO SlimefunOreChunks vDEV - 9 (git 88dd72b0)
23.11 12:50:18 [Server] INFO SensibleToolbox vDEV - 33 (git ca72a257)
23.11 12:50:18 [Server] INFO ExtraGear vDEV - 12 (git 4570ea2c)
23.11 12:50:18 [Server] INFO MoreTools vDEV - 8 (git db8d8814)
23.11 12:50:18 [Server] INFO ClayTech v1.2.18
23.11 12:50:18 [Server] INFO InfinityExpansion vDEV - 49 (git fe0b3707)
23.11 12:50:18 [Server] INFO SFCalc vDEV - 14 (git 8d205b67)
23.11 12:50:18 [Server] INFO ElectricSpawners vDEV - 18 (git f9da206b)
23.11 12:50:18 [Server] INFO WhatIsThis v3.2
23.11 12:50:18 [Server] INFO MobCapturer vDEV - 11 (git 4edf38dd)
23.11 12:50:18 [Server] INFO SlimyTreeTaps vDEV - 15 (git 205f8afc)
23.11 12:50:18 [Server] INFO PrivateStorage vDEV - 14 (git 98a31c90)
23.11 12:50:18 [Server] INFO TranscEndence vDEV - 21 (git f7bb1376)
23.11 12:50:18 [Server] INFO ColoredEnderChests vDEV - 17 (git f9a39e70)
23.11 12:50:18 [Server] INFO FluffyMachines vDEV - 45 (git 83a0ff9a)
23.11 12:50:18 [Server] INFO CMI v8.7.10.0
23.11 12:50:18 [Server] INFO ChestTerminal vDEV - 38 (git c024be5c)
23.11 12:50:18 [Server] INFO DyedBackpacks vDEV - 9 (git c42435c1)
23.11 12:50:18 [Server] INFO SoundMuffler vDEV - 17 (git 3abf8993)
23.11 12:50:18 [Server] INFO SlimefunWarfare vDEV - 9 (git fe18afc3)
23.11 12:50:18 [Server] INFO EcoPower vDEV - 2 (git b0c0c875)
23.11 12:50:18 [Server] INFO HotbarPets vDEV - 31 (git 5909202f)
23.11 12:50:18 [Server] INFO ExoticGarden vDEV - 61 (git b5067266)
23.11 12:50:18 [Server] INFO Barrels vDEV - 14 (git 1563de94)
23.11 12:50:18 [Server] INFO Liquid vDEV - 2 (git a1e713d8)
23.11 12:50:18 [Server] INFO LiteXpansion vDEV - 98 (git f79eab2f)
23.11 12:50:18 [Server] INFO SoulJars vDEV - 17 (git 9eedba0f)

 - Server Software (Spigot/Paper):
 - Minecraft Version: 1.16.3
 - Slimefun Version: Slimefun4 - DEV 737 (git 1c5f2).jar
 - CS-CoreLib Version:  CS-CoreLib+v1.6.3.jar

**Comment by poma123** [comment]
Please update your CS-Corelib version, you are using an outdated version.
