### ISSUE TITLE
Worlds selection in config.yml doesn't work

### ISSUE THREAD

**Issue by R4z0rX** [poma123/GlobalWarming#12]
Hi! This is what is hapening:
No matter what configs we try, we can't get GW to work in the world nuclear.
With any of following configs, inside the game we do:
_/gw pollution get world_
and we a get a value (that's correct), but when we do:
_/gw pollution get nuclear_
the response is always:
_The plugin's functionality is disabled in the given world_

As Blacklist (GW should work in all worlds):
```
worlds: []
world-filter-type: blacklist
```

Or as Whitelist (GW should work only in world and nuclear worlds):
```
worlds:
  - world
  - nuclear
world-filter-type: whitelist
```
The last one is even worst because the plugin parse config.yml and transform it to this:
```
worlds:
- world
- nuclear
world-filter-type: whitelist
```
And that's a wrong YML format for an array of elements, the 2 spaces before de - are needed.
In the end, the result is always the same, GW only works in the 3 vanilla worlds (world, world_nether, and world_the_end), but doesn't work in any additional world.
Just in case, nuclear is a normal type world, just like the overworld.

I hope you can find the bug.
Thanks in advance.

 - Server Software (Spigot/Paper): Paper v1_16_R2
 - Minecraft Version: MC 1.16.3
 - Slimefun Version: Slimefun vDEV - 766 (git 5aa5ca1a)
 - CS-CoreLib Version: CS-CoreLib vDEV - 91 (git e42a05d1)
 - GlobalWarming Version: GlobalWarming vDEV - 4 (git bd8e730a)

**Comment by poma123** [comment]
Hi there. Interesting, I will look into this.
Also, that's a valid YAML format, so both of them should work.

Can you please provide a server startup log?

**Comment by R4z0rX** [comment]
Hey! Thanks for your quick reply.
Are you really sure about that format? Because I parsed these (and other) configs with several YAML validators, and all of them format the array with 2 spaces before de - sign.
On the other hand, please sorry, I forgot to mention that we use Multiverse Core for world managment. Maybe, it is related to the way it loads the worlds.
I'll give you a full serv log at loading, when I get back home.
Thanks again!

**Comment by poma123** [comment]
Multiverse should work though, as I tested it.

**Comment by R4z0rX** [comment]
Here you have, the GW folder with the config.yml (that should work) and the rest of the configs, and the full startup latest.log.
I hope this could help. Let me know if you need anything else.
Thanks again!

[GW+Logs.zip](https://github.com/poma123/GlobalWarming/files/5706820/GW%2BLogs.zip)

**Comment by R4z0rX** [comment]
Well, I tried the last build with my last config...
```
worlds: []
world-filter-type: blacklist
```
And the night is dark and full of errors... xD

Here you have the logs and err files...
[logs.zip](https://github.com/poma123/GlobalWarming/files/5712138/logs.zip)

**Comment by poma123** [comment]
Finally fixed in build 6. Thanks for reporting it!

**Comment by poma123** [comment]
Finally fixed in build 6. Thanks for reporting!

**Comment by R4z0rX** [comment]
Yay! It's working! Thank you very much! 👍
