### ISSUE TITLE
Global warming needs to be updated for 1.18 biomes

### ISSUE THREAD

**Issue by Boomer-1** [poma123/GlobalWarming#26]
## Description (REQUIRED)

in the server logs, global warming does not support 1.18 biomes.

## Expected behavior (REQUIRED)

to support 1.18 biomes

## Server Log

https://pastebin.com/ZxihG0Gs

## Environment (REQUIRED)

 - Server Software (Spigot/Paper): paper 81 1.18
 - Minecraft Version: 1.18.1
 - Slimefun Version: 987
 - CS-CoreLib Version: n/a

**Comment by Zunwolf1896** [comment]
This temp fix has worked for me, deleted the missing biomes and replaced some of them with the new 1.18 biomes, I don't seem to be getting any errors in my console anymore - hope it works for you too. Just replace the text in the biomes.yml file with the follwing; 

`default-biome-temperatures:
  OCEAN: 18
  PLAINS: 24
  DESERT: 37
  WINDSWEPT_HILLS: 5
  FOREST: 18
  TAIGA: 12
  SWAMP: 15
  RIVER: 16
  NETHER_WASTES: 40
  THE_END: 0
  FROZEN_OCEAN: -10
  FROZEN_RIVER: -10
  SNOWY_PLAINS: -6
  MUSHROOM_FIELDS: 16
  BEACH: 23.5
  JUNGLE: 35
  SPARSE_JUNGLE: 27
  DEEP_OCEAN: 10
  STONY_SHORE: 14
  SNOWY_BEACH: 3
  BIRCH_FOREST: 20
  DARK_FOREST: 14
  SNOWY_TAIGA: 1
  OLD_GROWTH_PINE_TAIGA: 17
  WINDSWEPT_FOREST: 10
  SAVANNA: 28
  SAVANNA_PLATEAU: 27
  BADLANDS: 28
  WOODED_BADLANDS: 26
  SMALL_END_ISLANDS: 0
  END_MIDLANDS: 0
  END_HIGHLANDS: 0
  END_BARRENS: 0
  WARM_OCEAN: 25
  LUKEWARM_OCEAN: 20
  COLD_OCEAN: 2
  DEEP_LUKEWARM_OCEAN: 19.7
  DEEP_COLD_OCEAN: 2
  DEEP_FROZEN_OCEAN: -10
  THE_VOID: 0
  SUNFLOWER_PLAINS: 24
  WINDSWEPT_GRAVELLY_HILLS: 15
  FLOWER_FOREST: 24
  ICE_SPIKES: -13.5
  OLD_GROWTH_BIRCH_FOREST: 20
  OLD_GROWTH_SPRUCE_TAIGA: 12
  WINDSWEPT_SAVANNA: 21
  ERODED_BADLANDS: 23
  BAMBOO_JUNGLE: 26
  SOUL_SAND_VALLEY: 27
  CRIMSON_FOREST: 34
  WARPED_FOREST: 34
  BASALT_DELTAS: 25
max-temperature-drop-at-night:
  OCEAN: 12
  PLAINS: 10
  DESERT: 40
  WINDSWEPT_HILLS: 10
  FOREST: 8
  TAIGA: 14
  SWAMP: 7
  RIVER: 7
  NETHER_WASTES: 0
  THE_END: 0
  FROZEN_OCEAN: 15
  FROZEN_RIVER: 10
  SNOWY_PLAINS: 5
  MUSHROOM_FIELDS: 6
  BEACH: 13
  JUNGLE: 6
  SPARSE_JUNGLE: 6
  DEEP_OCEAN: 10
  STONY_SHORE: 12
  SNOWY_BEACH: 12
  BIRCH_FOREST: 11
  DARK_FOREST: 13
  SNOWY_TAIGA: 15
  OLD_GROWTH_SPRUCE_TAIGA: 15
  WINDSWEPT_FOREST: 14
  SAVANNA: 20
  SAVANNA_PLATEAU: 20
  BADLANDS: 20
  WOODED_BADLANDS: 20
  SMALL_END_ISLANDS: 0
  END_MIDLANDS: 0
  END_HIGHLANDS: 0
  END_BARRENS: 0
  WARM_OCEAN: 8
  LUKEWARM_OCEAN: 6
  COLD_OCEAN: 7
  DEEP_LUKEWARM_OCEAN: 6
  DEEP_COLD_OCEAN: 7
  DEEP_FROZEN_OCEAN: 10
  THE_VOID: 0
  SUNFLOWER_PLAINS: 10
  WINDSWEPT_GRAVELLY_HILLS: 7
  FLOWER_FOREST: 10
  ICE_SPIKES: 12
  OLD_GROWTH_BIRCH_FOREST: 12
  OLD_GROWTH_SPRUCE_TAIGA: 14
  WINDSWEPT_SAVANNA: 18
  ERODED_BADLANDS: 18
  BAMBOO_JUNGLE: 8
  SOUL_SAND_VALLEY: 0
  CRIMSON_FOREST: 0
  WARPED_FOREST: 0
  BASALT_DELTAS: 0`
