### ISSUE TITLE
Disappearance of canisters

### ISSUE THREAD

**Issue by 100petr** [poma123/GlobalWarming#31]
## Description (REQUIRED)

Players have repeatedly complained to me that their empty canisters are disappearing. Probably the ones that are being filled at the time of reboot are deleted

## Steps to reproduce the Issue (REQUIRED)

Insert an empty canister into the air compressor
Restart the server
See

## Expected behavior (REQUIRED)

Empty canisters will not disappear

## Environment (REQUIRED)

 - Server Software (Spigot/Paper): Purpur 1.18.1
 - Minecraft Version: 1.18.1
 - Slimefun Version: dev #999

**Comment by poma123** [comment]
Well that's how SF machines work, currently this is intended, and not an issue.
